### ISSUE TITLE
It is not supported in version 3.35. Is there any way to solve it?

### ISSUE THREAD

**Issue by habbyCP** [MecAtlantiss/StormforgeThreatMeter#1]
Bro, can you fix it?

**Comment by MecAtlantiss** [comment]
The addon relies on the game server sending messages to each player's client with the threat amounts. Initially, the 3.3.5 clients weren't receiving these messages. The developer of Stormforge TBC servers recently started sending the messages to the 3.3.5 client, so the addon should now work on both the 2.4.3 and 3.3.5 client. You just need to enable loading out of date addons on the character list screen. The addon's font is smaller on the 3.3.5 client than the 2.4.3 client and I'm not yet sure why. I will likely do more work on this addon for the next Stormforge TBC server.
